ALTER TABLE users ADD COLUMN IF NOT EXISTS tier VARCHAR(20) NOT NULL DEFAULT 'standard';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

ALTER TABLE vaults ADD COLUMN IF NOT EXISTS yield_earned NUMERIC(20,8) NOT NULL DEFAULT 0;
ALTER TABLE vaults ADD COLUMN IF NOT EXISTS fees_paid NUMERIC(20,8) NOT NULL DEFAULT 0;
ALTER TABLE vaults ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;

ALTER TABLE allocations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE allocations ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE settlements ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS estimated_fee NUMERIC(20,8);
